# Generated by Django 3.2.18 on 2023-04-30 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=30)),
                ('mobile', models.CharField(max_length=300)),
                ('emailid', models.EmailField(max_length=40)),
                ('adress', models.CharField(max_length=20)),
            ],
        ),
    ]
