# Generated by Django 3.2.18 on 2023-05-03 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internship', '0003_admlogin'),
    ]

    operations = [
        migrations.CreateModel(
            name='usertimings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('InTime', models.TimeField()),
                ('Work', models.CharField(max_length=100)),
                ('OutTime', models.TimeField()),
                ('signature', models.CharField(max_length=20)),
            ],
        ),
    ]
