# Generated by Django 3.2.18 on 2023-05-03 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internship', '0004_usertimings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertimings',
            name='InTime',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='usertimings',
            name='OutTime',
            field=models.CharField(max_length=100),
        ),
    ]
